title: 包寒吴霜
subtitle: Han-Wu-Shuang (Bruce) Bao
description: 包寒吴霜
keywords: 包寒吴霜, 包寒, 吴霜
author: 包寒吴霜
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: img/photo-bhws.jpg
google_analytics: UA-172970823-1
# favicon: img/favicon.ico